/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as URouteRouteImport } from './routes/u/route'
import { Route as UIndexRouteImport } from './routes/u/index'
import { Route as UIdIndexRouteImport } from './routes/u/$id/index'
import { Route as UChatIndexRouteImport } from './routes/u/chat/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const URouteRoute = URouteRouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => URouteRoute,
} as any)
const UIdIndexRoute = UIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => URouteRoute,
} as any)
const UChatIndexRoute = UChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => URouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u': typeof URouteRouteWithChildren
  '/u/': typeof UIndexRoute
  '/u/$id/': typeof UIdIndexRoute
  '/u/chat/': typeof UChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u': typeof UIndexRoute
  '/u/$id': typeof UIdIndexRoute
  '/u/chat': typeof UChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u': typeof URouteRouteWithChildren
  '/u/': typeof UIndexRoute
  '/u/$id/': typeof UIdIndexRoute
  '/u/chat/': typeof UChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/u' | '/u/' | '/u/$id/' | '/u/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/u' | '/u/$id' | '/u/chat'
  id: '__root__' | '/' | '/u' | '/u/' | '/u/$id/' | '/u/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  URouteRoute: typeof URouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/': {
      id: '/u/'
      path: '/'
      fullPath: '/u/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof URouteRoute
    }
    '/u/$id/': {
      id: '/u/$id/'
      path: '/$id'
      fullPath: '/u/$id/'
      preLoaderRoute: typeof UIdIndexRouteImport
      parentRoute: typeof URouteRoute
    }
    '/u/chat/': {
      id: '/u/chat/'
      path: '/chat'
      fullPath: '/u/chat/'
      preLoaderRoute: typeof UChatIndexRouteImport
      parentRoute: typeof URouteRoute
    }
  }
}

interface URouteRouteChildren {
  UIndexRoute: typeof UIndexRoute
  UIdIndexRoute: typeof UIdIndexRoute
  UChatIndexRoute: typeof UChatIndexRoute
}

const URouteRouteChildren: URouteRouteChildren = {
  UIndexRoute: UIndexRoute,
  UIdIndexRoute: UIdIndexRoute,
  UChatIndexRoute: UChatIndexRoute,
}

const URouteRouteWithChildren =
  URouteRoute._addFileChildren(URouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  URouteRoute: URouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
