import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, join } from "node:path";
import { workspaceId } from "./ulid.js";

const NUSA_DIR = ".nusa";
const CONFIG_VERSION = 1;

export async function init(_args) {
  const cwd = process.cwd();
  const root = join(cwd, NUSA_DIR);

  if (existsSync(root)) {
    console.error(`.nusa/ already exists at ${root}. Nothing to do.`);
    process.exit(1);
  }

  await mkdir(join(root, "docs/plan"), { recursive: true });
  await mkdir(join(root, "agents"), { recursive: true });
  await mkdir(join(root, "skills"), { recursive: true });

  const config = {
    id: workspaceId(),
    version: CONFIG_VERSION,
  };
  await writeFile(
    join(root, "config.json"),
    JSON.stringify(config, null, 2) + "\n",
  );

  await writeFile(
    join(root, ".gitignore"),
    ["config.local.json", "cache/", "*.log", ""].join("\n"),
  );

  await writeFile(
    join(root, "README.md"),
    [
      "# .nusa workspace",
      "",
      "Auto-generated by `nusa init`. Edit at will.",
      "",
      "## Layout",
      "",
      "- `config.json` — workspace id (persistent identity) + schema version",
      "- `docs/plan/<name>.md` — plan spec",
      "- `docs/plan/<name>.progress.md` — live progress log",
      "- `agents/<name>/prompt.md` — agent system prompt",
      "- `agents/<name>/config.json` — agent runtime config",
      "- `skills/<name>/desc.md` — skill description",
      "- `skills/<name>/scripts/<script>.{js,py}` — skill scripts",
      "",
      "Run `nusa serve` from anywhere inside this workspace to start the harness.",
      "",
    ].join("\n"),
  );

  console.log(`Initialized .nusa/ at ${resolve(root)}`);
  console.log(`  workspace_id: ${config.id}`);
  console.log("");
  console.log("Next: edit .nusa/agents/, .nusa/skills/, .nusa/docs/plan/");
  console.log("Then run `nusa serve`.");
}