// Hand-written chat streaming helpers (NOT generated by openapi-ts).
//
// NOTE: kept in src/lib/ (not src/lib/api/) so `openapi-ts` regeneration
// (default `clean: true`) never wipes it.

import type { ChatMessage, SseEvent } from "@/lib/chat-types";

export const API_BASE_URL: string =
	import.meta.env.VITE_API_BASE_URL ?? "http://localhost:3001";

/**
 * Load session message history.
 * Backend: GET /api/sessions/:id/messages -> { messages: [{ role, content }] }
 */
export async function fetchMessages(
	baseUrl: string,
	sessionId: string,
): Promise<ChatMessage[]> {
	const res = await fetch(`${baseUrl}/api/sessions/${sessionId}/messages`);
	if (!res.ok) {
		throw new Error(
			`Failed to load messages (HTTP ${res.status})`,
		);
	}
	const body = (await res.json()) as { messages?: ChatMessage[] };
	return Array.isArray(body.messages) ? body.messages : [];
}

/**
 * Send a message and stream run events back via SSE.
 * Backend: POST /api/sessions/:id/stream -> text/event-stream
 * Each SSE data payload is a SseEvent; stream ends with { type: "__end__" }.
 */
export async function* streamChatMessage(
	baseUrl: string,
	sessionId: string,
	body: {
		message: string;
		configDir: string;
		agentProfile?: string;
		model?: string;
	},
	signal?: AbortSignal,
): AsyncGenerator<SseEvent> {
	const res = await fetch(`${baseUrl}/api/sessions/${sessionId}/stream`, {
		method: "POST",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(body),
		signal,
	});

	if (!res.ok || !res.body) {
		let message = `Stream failed (HTTP ${res.status})`;
		try {
			const err = (await res.json()) as { error?: string };
			if (err?.error) message = err.error;
		} catch {
			// keep default message
		}
		throw new Error(message);
	}

	const reader = res.body.getReader();
	const decoder = new TextDecoder();
	let buffer = "";

	try {
		while (true) {
			const { done, value } = await reader.read();
			if (done) break;
			buffer += decoder.decode(value, { stream: true });

			let sep: number;
			while ((sep = buffer.indexOf("\n\n")) !== -1) {
				const rawEvent = buffer.slice(0, sep);
				buffer = buffer.slice(sep + 2);
				for (const line of rawEvent.split("\n")) {
					if (!line.startsWith("data: ")) continue;
					const payload = line.slice("data: ".length);
					if (!payload) continue;
					let event: SseEvent;
					try {
						event = JSON.parse(payload) as SseEvent;
					} catch {
						continue;
					}
					yield event;
					if (event.type === "__end__") return;
				}
			}
		}
	} finally {
		reader.releaseLock();
	}
}