// Hand-written SSE firehose + run-control helpers (NOT generated by openapi-ts).
//
// NOTE: kept in src/lib/ (not src/lib/api/) so `openapi-ts` regeneration
// (default `clean: true`) never wipes it.
//
// Exports:
//   API_BASE_URL     — backend base URL (env override)
//   fetchMessages    — GET /api/sessions/:id/messages (backfill)
//   startRun         — POST /api/sessions/:id/stream, returns { runId }
//   cancelRun        — POST /api/sessions/:id/cancel
//   connectStream    — GET /api/sessions/stream, parses StreamEvent envelopes

import type { ChatMessage, StreamEvent } from "@/lib/chat-types";

export const API_BASE_URL: string =
	import.meta.env.VITE_API_BASE_URL ?? "http://localhost:3001";

/**
 * Load session message history.
 * Backend: GET /api/sessions/:id/messages -> { messages, activeCheckpointId? }
 */
export async function fetchMessages(
	baseUrl: string,
	sessionId: string,
): Promise<{ messages: ChatMessage[]; activeCheckpointId?: string }> {
	const res = await fetch(`${baseUrl}/api/sessions/${sessionId}/messages`);
	if (!res.ok) {
		throw new Error(
			`Failed to load messages (HTTP ${res.status})`,
		);
	}
	const body = (await res.json()) as {
		messages?: ChatMessage[];
		activeCheckpointId?: string;
	};
	return {
		messages: Array.isArray(body.messages) ? body.messages : [],
		activeCheckpointId: body.activeCheckpointId,
	};
}

/**
 * Preflight a run on an existing session. The backend detaches the run and
 * relays its events over the global firehose (GET /api/sessions/stream).
 * Backend: POST /api/sessions/:id/stream -> 202 { runId, status }
 */
export async function startRun(
	baseUrl: string,
	sessionId: string,
	body: {
		message: string;
		configDir: string;
		agentProfile: string;
		model?: string;
	},
): Promise<{ runId: string }> {
	const res = await fetch(`${baseUrl}/api/sessions/${sessionId}/stream`, {
		method: "POST",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(body),
	});

	if (!res.ok) {
		let message = `Failed to start run (HTTP ${res.status})`;
		try {
			const err = (await res.json()) as { error?: string };
			if (err?.error) message = err.error;
		} catch {
			// keep default message
		}
		throw new Error(message);
	}

	const parsed = (await res.json()) as { runId?: string; status?: string };
	if (!parsed.runId) {
		throw new Error("Backend did not return a runId");
	}
	return { runId: parsed.runId };
}

/**
 * Fork or replace a past human message and start a run on the new branch.
 * Backend: POST /api/sessions/:id/restart -> 202 { runId, checkpointId, status }
 */
export async function restartFromCheckpoint(
	baseUrl: string,
	sessionId: string,
	body: {
		checkpointId: string;
		message: string;
		configDir: string;
		agentProfile: string;
		model?: string;
	},
): Promise<{ runId: string; checkpointId: string }> {
	const res = await fetch(`${baseUrl}/api/sessions/${sessionId}/restart`, {
		method: "POST",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(body),
	});

	if (!res.ok) {
		let message = `Failed to restart (HTTP ${res.status})`;
		try {
			const err = (await res.json()) as { error?: string };
			if (err?.error) message = err.error;
		} catch {
			// keep default
		}
		throw new Error(message);
	}

	const parsed = (await res.json()) as {
		runId?: string;
		checkpointId?: string;
	};
	if (!parsed.runId || !parsed.checkpointId) {
		throw new Error("Backend did not return runId + checkpointId");
	}
	return { runId: parsed.runId, checkpointId: parsed.checkpointId };
}

/**
 * Move the session's active branch pointer to a sibling checkpoint.
 * Backend: POST /api/sessions/:id/switch-branch -> 200 { activeCheckpointId }
 */
export async function switchBranch(
	baseUrl: string,
	sessionId: string,
	checkpointId: string,
): Promise<{ activeCheckpointId: string }> {
	const res = await fetch(
		`${baseUrl}/api/sessions/${sessionId}/switch-branch`,
		{
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify({ checkpointId }),
		},
	);
	if (!res.ok) {
		let message = `Failed to switch branch (HTTP ${res.status})`;
		try {
			const err = (await res.json()) as { error?: string };
			if (err?.error) message = err.error;
		} catch {
			// keep default
		}
		throw new Error(message);
	}
	const parsed = (await res.json()) as { activeCheckpointId?: string };
	if (!parsed.activeCheckpointId) {
		throw new Error("Backend did not return activeCheckpointId");
	}
	return { activeCheckpointId: parsed.activeCheckpointId };
}

/**
 * Explicitly cancel the active run of a session. The backend's detached
 * consumer publishes a "cancelled" envelope on the firehose in response.
 * Backend: POST /api/sessions/:id/cancel -> 200 { status: "cancelled" }
 */
export async function cancelRun(baseUrl: string, sessionId: string): Promise<void> {
	const res = await fetch(`${baseUrl}/api/sessions/${sessionId}/cancel`, {
		method: "POST",
	});

	if (!res.ok) {
		let message = `Failed to cancel run (HTTP ${res.status})`;
		try {
			const err = (await res.json()) as { error?: string };
			if (err?.error) message = err.error;
		} catch {
			// keep default message
		}
		throw new Error(message);
	}
}

/**
 * Open the global SSE firehose. Each `data: {json}` frame is parsed into a
 * StreamEvent and passed to onEvent. Resolves when the server closes the
 * stream; rejects on HTTP/network/abort errors. Reconnect is NOT handled
 * here — the StreamProvider owns reconnection.
 * Backend: GET /api/sessions/stream
 */
export async function connectStream(
	baseUrl: string,
	onEvent: (event: StreamEvent) => void,
	signal?: AbortSignal,
): Promise<void> {
	const res = await fetch(`${baseUrl}/api/sessions/stream`, { signal });

	if (!res.ok || !res.body) {
		let message = `Stream failed (HTTP ${res.status})`;
		try {
			const err = (await res.json()) as { error?: string };
			if (err?.error) message = err.error;
		} catch {
			// keep default message
		}
		throw new Error(message);
	}

	const reader = res.body.getReader();
	const decoder = new TextDecoder();
	let buffer = "";

	try {
		while (true) {
			const { done, value } = await reader.read();
			if (done) break;
			buffer += decoder.decode(value, { stream: true });

			let sep: number;
			while ((sep = buffer.indexOf("\n\n")) !== -1) {
				const rawEvent = buffer.slice(0, sep);
				buffer = buffer.slice(sep + 2);
				for (const line of rawEvent.split("\n")) {
					// Heartbeats are comments (": keepalive") — skipped here.
					if (!line.startsWith("data: ")) continue;
					const payload = line.slice("data: ".length);
					if (!payload) continue;
					try {
						onEvent(JSON.parse(payload) as StreamEvent);
					} catch {
						// malformed frame — skip, keep the stream alive
					}
				}
			}
		}
	} finally {
		reader.releaseLock();
	}
}